[indicator]
preview = {}
current = { fg = "#221727", bg = "#eee9ff" }
parent = { fg = "#221727", bg = "#eee9ff" }

[mgr]
cwd = { fg = "#221727", bg = "#221727" }

[pick]
border = { fg = "#CFAAF3" }

[pick.active]
fg = "#eee9ff"
bg = "#2A2340"

[pick.inactive]
fg = "#eee9ff"

[input]
border = { fg = "#CFAAF3" }
title = { fg = "#eee9ff" }
value = { fg = "#eee9ff" }
selected = { reversed = true }

[confirm]
border = { fg = "#CFAAF3" }
title = { fg = "#eee9ff" }
body = { fg = "#eee9ff" }
list = { fg = "#eee9ff" }
btn_yes = { reversed = true }
btn_no = { fg = "#eee9ff" }
