[mgr]
show_hidden = true

[opener]
code = [{ run = '/usr/local/bin/cursor "$@"', block = true, desc = "Cursor" }]
opencode = [
  { run = 'kitty @ launch --type=tab --cwd="$@" -- zsh -c opencode', desc = "Opencode" },
]
terminal = [{ run = 'kitty @ launch --type=tab --cwd="$@"', desc = "Terminal" }]
edit = [{ run = 'vim "$@"', block = true, desc = "Vim" }]
reveal = [
  { run = 'open -R "$@"', for = "macos", desc = "Finder" },
  { run = 'xdg-open "$(dirname "$@")"', for = "linux", desc = "File Manager" },
]

[open]
rules = [
  { url = "*", use = [
    "edit",
    "code",
  ] },
  { url = "*/", use = [
    "code",
    "opencode",
    "terminal",
    "reveal",
  ] },
]
